version: "3"
 
services:
  app:
    build: .
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      RABBIT_URL: amqp://rabbitmq:5672
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq
    user: node
    command: sh -c './wait-for.sh rabbitmq:15672 -- npm start'
      
  rabbitmq:
    image: "rabbitmq:management"
    ports:
      - "5672:5672"
      - "15672:15672"
